# Generated by Django 2.0.5 on 2018-05-21 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RESTApi', '0002_auto_20180516_1822'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Hardware',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='HardwarePiece',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hardware', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RESTApi.Hardware')),
            ],
        ),
        migrations.CreateModel(
            name='HardwareRental',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rental_date', models.DateTimeField()),
                ('return_date', models.DateTimeField()),
                ('hardware_piece', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RESTApi.HardwarePiece')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RESTApi.Profile')),
            ],
        ),
        migrations.AlterField(
            model_name='article',
            name='article_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RESTApi.ArticleType'),
        ),
    ]
