# Generated by Django 2.0.5 on 2018-06-08 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RESTApi', '0004_textinfo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TextInfo',
            new_name='AboutData',
        ),
    ]
